### ISSUE TITLE
Kan ikke sende PR om det er for mange bilder vedlagt?

### ISSUE THREAD

**Issue by camyrland** [kodeklubben/lessoneditor#250]
Ene oppgaveforfatteren får ikke sendt inn PR på oppgaver til Scratch Jr, mistenker at det er for mange (??) bilder som må sendes inn siden Scratch Jr ikke har kodegenerator

**Comment by mijohansen** [comment]
Denne saken må sees på som blokkerende. Vi tar tak i den asap.
