### ISSUE TITLE
Gjør om Lego Mindstorms-kategori til bare "Lego"

### ISSUE THREAD

**Issue by camyrland** [kodeklubben/lessoneditor#260]
Så kan vi differensiere på WeDo, Spike og Mindstorms i oppgavetittel, som vi gjør med PXT og Python i Micro:bit-kategorien

**Comment by sagatun** [comment]
OK, det er en enkel sak. Men må vel kanskje endre navnet på mappa i github-repoet og?  Heter "legomindstorms" i dag.
