### ISSUE TITLE
Må få opp et fungerende utviklermiljø igjen. 

### ISSUE THREAD

**Issue by sagatun** [kodeklubben/lessoneditor#485]
Utviklermiljøet krasjer.  Er nok noen pakker som har blitt oppdatert siden sist.   

Må få opp et fungerende utviklermiljø. Kan da samtidig forbedre dagens Docker-løsning.

**Comment by SergioDaroca** [comment]
Hei alle!
Er lessoneditor ment å være installert på en webside, som sagt lenge siden på slacks liksom lessoneditor.kodeklubben.no?
Jeg nedlastet den men det gikk feil uten stopp pga ny node versjon og videre, kunne ikke installere den.  Jeg kan ha litt tid i uka til å prøve igjen og gi tilbakkemelding. Lagde ny oppgave og sendte pull request, Algoritmia. Håper noen har tid å se på den. snakkes!

**Comment by SergioDaroca** [comment]
Hei!
Jeg forked og startet en ny branch på lessoneditor: https://github.com/SergioDaroca/lessoneditor/tree/libraryUpdates
Jeg var ikke så vant til npm, NX, typescript, men det er jeg nå litt :D
Jeg oppdaterte alle librairies til siste versjon, fant og fikset mange problemer med breaking endringer og fikk det i det minste til å installere  ten feil og build/kompilere contracts lib riktig.
NX har endret seg mye og har ikke helt helt fixet webpack compatibilitet (mangel av executors, workspace endring, mye refactoring m.m.), jeg måtte re-scope mange ting, men jeg vet ikke engang om tragets jeg konfigurerte er de riktige.
frontend og thumbnailer gjennom webpack gir flere typescript feil ut for nå, men de ser nesten alle like.
Nestbackend må jeg se enda nærmere.
Jeg skal prøve å skrive litt mer presiss før i morgen, og sende opp pull request så dere kan se mer nøyaktig hvor lite progress jeg fikk så vi kan se om det hjelper noe...
Vi snakkes!

**Comment by SergioDaroca** [comment]
https://github.com/kodeklubben/lessoneditor/compare/main...SergioDaroca:lessoneditor:libraryUpdates
for å se rask på endringer til nå
